# Generated by Django 4.2.27 on 2025-12-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_bio'),
        ('accounts', '0002_remove_customuser_followers_customuser_following_and_more'),
    ]

    operations = [
    ]
