"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=aadgw(8sdrgnh#en)40&7&$1b9o@z32940#!g)3zpclxx_tau'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

APPEND_SLASH = True
SECURE_BROWSER_XSS_FILTER = True          # enables XSS filtering in the browser
X_FRAME_OPTIONS = 'DENY'                  # prevents clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True        # prevents content type sniffing

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# 🔒 HSTS for HTTPS
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    # ... other middleware
    'csp.middleware.CSPMiddleware',
]

CSP_DEFAULT_SRC = ("'self'",)   # Only allow resources from your domain
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", 'data:')

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/books/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# SECURITY MEASURES:
# - DEBUG=False: Prevents debug information leak in production
# - SECURE_BROWSER_XSS_FILTER=True: Browser XSS protection
# - X_FRAME_OPTIONS='DENY': Prevents clickjacking
# - SECURE_CONTENT_TYPE_NOSNIFF=True: Prevents content sniffing
# - CSRF_COOKIE_SECURE & SESSION_COOKIE_SECURE=True: Only send cookies over HTTPS
# - CSP headers: Restrict external scripts, styles, and images
# - All ORM queries use parameterized queries to prevent SQL injection
# - CSRF token included in all forms
# SECURITY SETTINGS FOR HTTPS

# Redirect all HTTP requests to HTTPS
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Instruct browsers to only use HTTPS for the next 1 year (31536000 seconds)
SECURE_HSTS_SECONDS = 31536000

# Include all subdomains in HSTS policy
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Allow HSTS preload lists (optional but recommended for public sites)
SECURE_HSTS_PRELOAD = True
# Ensure cookies are sent only via HTTPS
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# Browser security headers
X_FRAME_OPTIONS = 'DENY'               # Prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True     # Prevent content type sniffing
SECURE_BROWSER_XSS_FILTER = True       # Enable browser XSS protection
server {
    listen 80;
    server_name yourdomain.com;
    return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
}

server {
    listen 443 ssl;
    server_name yourdomain.com;

    ssl_certificate /etc/ssl/certs/your_cert.crt;
    ssl_certificate_key /etc/ssl/private/your_key.key;

    location / {
        proxy_pass http://127.0.0.1:8000;  # your Django app
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
# Tell Django that the request is secure when the proxy sets this header
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ------------------ HTTPS & Security Settings ------------------
# SECURE_SSL_REDIRECT: Redirect all HTTP traffic to HTTPS
# SECURE_HSTS_SECONDS: HSTS policy, instructs browsers to use HTTPS for 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS: HSTS for all subdomains
# SECURE_HSTS_PRELOAD: Preload HTTPS in browsers
# SESSION_COOKIE_SECURE: Ensures session cookies sent over HTTPS only
# CSRF_COOKIE_SECURE: Ensures CSRF cookie sent over HTTPS only
# X_FRAME_OPTIONS: Deny framing to prevent clickjacking
# SECURE_CONTENT_TYPE_NOSNIFF: Prevent MIME type sniffing
# SECURE_BROWSER_XSS_FILTER: Enable browser XSS filter


